#!/usr/bin/env python

Import( '*' )

class CModule:
    def mod_src( self ):
        files = env.get_source_files();
        rfiles = [];
        obj_file = "";
        obj_file_package = "";
        
        for file in files:
            if file.endswith( "object/object_extension.d" ): rfiles.append( file );
            if file.endswith( "object/pool.d" ): rfiles.append( file );
            if file.endswith( "object/util_classes.d" ): rfiles.append( file );
            if file.endswith( "object/_object.d" ): rfiles.append( file );
            if file.endswith( "object/serialize.d" ): rfiles.append( file );
            if file.endswith( "object/util_cdc.d" ): rfiles.append( file );
            if file.endswith( "object/class_description.d" ): rfiles.append( file );
            if file.endswith( "object/package.d" ): rfiles.append( file );

        for file in rfiles:
            files.remove( file );
            files.append( file );

        return files;

    def mod_build( self ):
        return env.CLibraryBR();

    def mod_sub( self ):
        return [
            "core_containers",
            "core_mem",
        ];

env.reg_module( "core", CModule() );