#!/usr/bin/env python

Import( '*' )

class CModule:
    def mod_src( self ):
        return env.get_source_files();

    def mod_build( self ):
        return env.CProgramBR();

    def mod_sub( self ):
        return [
            "game"
        ];

if env.build_mode == "debug":
    env.reg_module( "exec", CModule() );
else:
    env.reg_module( "breach", CModule() );

